### ISSUE TITLE
expo run:ios command fails to build ios project

### ISSUE THREAD

**Issue by edwin-pan** [fs-eire/ort-rn-hello-world#1]
Hi! Thanks for this repo. It's been very helpful for getting oriented with a minimum working example. To preface, I am new to react native so bare with me (any pointers welcome!). 

I am running into this issue with the build, with a clean pull. 

To start, I set myself up with node v14
0. Run `nvm install 14`
```bash
Downloading and installing node v14.21.3...
Downloading https://nodejs.org/dist/v14.21.3/node-v14.21.3-darwin-x64.tar.xz...
######################################################################################################################################################################################### 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v14.21.3 (npm v6.14.18)
```

I then walk through your commands and get as far as running `expo run:ios`, which fails on build. Looking forward to your reply! Please let me know if you need more information from my side. 

1. Run `npm install -g expo-cli`
```bash
npm WARN deprecated expo-cli@6.3.10: The global Expo CLI has been superseded by 'npx expo' and eas-cli –– Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
/Users/edwinpan/.nvm/versions/node/v14.21.3/bin/expo -> /Users/edwinpan/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/bin/expo.js
/Users/edwinpan/.nvm/versions/node/v14.21.3/bin/expo-cli -> /Users/edwinpan/.nvm/versions/node/v14.21.3/lib/node_modules/expo-cli/bin/expo.js
npm WARN @expo/webpack-config@18.1.0 requires a peer of expo@^48.0.17 but none is installed. You must install peer dependencies yourself.
npm WARN expo-pwa@0.0.125 requires a peer of expo@* but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

+ expo-cli@6.3.10
added 938 packages from 580 contributors in 37.967s
```
2. Run `npm install -g yarn`
```bash
> yarn@1.22.19 preinstall /Users/edwinpan/.nvm/versions/node/v14.21.3/lib/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

/Users/edwinpan/.nvm/versions/node/v14.21.3/bin/yarn -> /Users/edwinpan/.nvm/versions/node/v14.21.3/lib/node_modules/yarn/bin/yarn.js
/Users/edwinpan/.nvm/versions/node/v14.21.3/bin/yarnpkg -> /Users/edwinpan/.nvm/versions/node/v14.21.3/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.19
added 1 package in 0.763s
```

3. Run `expo init . -t expo-template-blank-typescript`
```bash 
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   The global expo-cli package has been deprecated.                        │
│                                                                           │
│   The new Expo CLI is now bundled in your project in the expo package.    │
│   Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.        │
│                                                                           │
│   To use the local CLI instead (recommended in SDK 46 and higher), run:   │
│   › npx expo <command>                                                    │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘

Migrate to using:
› npx create-expo-app --template


The directory ort-rn-hello-world has files that might be overwritten:

  .expo
  .expo-shared
  App.tsx
  README.md
  app.json
  assets
  babel.config.js
  index.js
  metro.config.js
  package.json
  tsconfig.json
  yarn.lock

Try using a new directory name, or moving these files.

(base) edwinpan@iEdwin-Pro-89:~/garage/code/ort-rn-hello-world$ yarn
yarn install v1.22.19
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[4/4] 🔨  Building fresh packages...
✨  Done in 5.87s.
```

4. Run `expo prebuild`
```bash 
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   The global expo-cli package has been deprecated.                        │
│                                                                           │
│   The new Expo CLI is now bundled in your project in the expo package.    │
│   Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.        │
│                                                                           │
│   To use the local CLI instead (recommended in SDK 46 and higher), run:   │
│   › npx expo <command>                                                    │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
✔ Created native projects | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 1723ms
✔ Config synced
✔ Installed pods and initialized Xcode workspace.
```

5. Run `expo run:ios`
```bash
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   The global expo-cli package has been deprecated.                        │
│                                                                           │
│   The new Expo CLI is now bundled in your project in the expo package.    │
│   Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.        │
│                                                                           │
│   To use the local CLI instead (recommended in SDK 46 and higher), run:   │
│   › npx expo <command>                                                    │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
› Planning build
› Compiling react-native Pods/RCT-Folly » json_pointer.cpp
› Compiling react-native Pods/Yoga » log.cpp
› Compiling react-native Pods/Yoga » experiments.cpp
› Compiling react-native Pods/Yoga » event.cpp
› Compiling react-native Pods/Yoga » Yoga.cpp

❌  (node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2289:9)

  2287 |         generationCount);
  2288 |     node->setLayoutHadOverflow(
> 2289 |         node->getLayout().hadOverflow() |
       |         ^ use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
  2290 |         currentRelativeChild->getLayout().hadOverflow());
  2291 |   }
  2292 |   return deltaFreeSpace;

› Compiling react-native Pods/Yoga » YGValue.cpp
› Compiling react-native Pods/Yoga » YGStyle.cpp
› Compiling react-native Pods/Yoga » YGNodePrint.cpp
› Compiling react-native Pods/glog » vlog_is_on.cc
› Compiling react-native Pods/glog » raw_logging.cc
› Compiling react-native Pods/Yoga » Yoga-dummy.m
› Compiling react-native Pods/Yoga » YGNode.cpp
› Executing onnxruntime-react-native Pods/onnxruntime-mobile-c » [CP] Copy XCFrameworks
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'OrtReactNativeHelloWorld' from project 'OrtReactNativeHelloWorld')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'OrtReactNativeHelloWorld' from project 'OrtReactNativeHelloWorld')

› 1 error(s), and 3 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
```

**Comment by fs-eire** [comment]
expo and react-native versions are bumping rapidly. perhaps the version in this demo repo is too old to work. could you try if it works in latest package versions?

**Comment by edwin-pan** [comment]
Thanks for the quick reply! I've forked and updated the package versions. It's publicly accessible here. 

edwin-pan/ort-rn-hello-world@d468f6a48e0b02d7594830056e9cc86fc4850a69

I'm not sure if the pre-build steps are still necessary... I get some strange error (see below). 
```bash
(base) edwinpan@iEdwin-Pro-89:~/garage/code/debug/ort-rn-hello-world$ npx expo prebuild
✔ Created native projects | gitignore skipped
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using yarn
> yarn install
Error: yarnpkg exited with non-zero code: 1
Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/edwinpan/garage/code/debug/ort-rn-hello-world/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:627:26)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:512:28)
    at Pipe.<anonymous> (node:net:334:12)
    ...
    at spawnAsync (/Users/edwinpan/garage/code/debug/ort-rn-hello-world/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at YarnPackageManager.runAsync (/Users/edwinpan/garage/code/debug/ort-rn-hello-world/node_modules/@expo/package-manager/build/node/BasePackageManager.js:38:42)
    at /Users/edwinpan/garage/code/debug/ort-rn-hello-world/node_modules/@expo/package-manager/build/node/YarnPackageManager.js:32:114
    at /Users/edwinpan/garage/code/debug/ort-rn-hello-world
/node_modules/@expo/package-manager/build/utils/spawn.js:19:34
```

Alternatively, if I just go straight into running it with `npm run ios`, the simulator starts but the model won't load. 
<img width="449" alt="Screenshot 2023-07-31 at 3 03 54 PM" src="https://github.com/fs-eire/ort-rn-hello-world/assets/30252980/2ccbefed-f22b-4983-a3c3-d5fc1575a755">

Here's the terminal traceback when I press that button. 
```bash
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Can't load a model: Cannot read property 'loadModel' of null
Error: Can't load a model: Cannot read property 'loadModel' of null
    at ?anon_0_ (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:131818:28)
    at next (native)
    at asyncGeneratorStep (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6092:26)
    at _next (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6111:29)
    at anonymous (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6116:14)
    at tryCallTwo (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6108:25)
    at apply (native)
    at loadModel (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:131822:34)
    at ?anon_0_ (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:131935:34)
    at next (native)
    at asyncGeneratorStep (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6092:26)
    at _next (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6111:29)
    at anonymous (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6116:14)
    at tryCallTwo (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6108:25)
    at apply (native)
    at createSessionHandler (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:131939:45)
    at ?anon_0_ (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:131705:47)
    at next (native)
    at asyncGeneratorStep (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6092:26)
    at _next (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:6111:29)
    at tryCallOne (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/private/var/folders/jn/gzcsy64949z2ltp7y741qlt80000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39751:26)
    at _callTimer (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39630:17)
    at _callReactNativeMicrotasksPass (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39675:17)
    at callReactNativeMicrotasks (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:39881:44)
    at __callReactNativeMicrotasks (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3696:46)
    at anonymous (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3470:45)
    at __guard (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3669:15)
    at flushedQueue (http://192.168.200.57:8081/node_modules/expo/AppEntry.bundle//&platform=ios&dev=true&hot=false&lazy=true:3469:21)


```

**Comment by edwin-pan** [comment]
Got it to work! Turns out the steps in @fs-eire's original tutorial work quite well. The version on my fork confirmed works on my machine. Cheers.
